### ISSUE TITLE
Vending Machine Audit Logging

### ISSUE THREAD

**Issue by mich181189** [londonhackspace/acserver-django#17]
Because the vending machine handles actual cash and items, the logging needs to be good. What I propose here is a text file log to act as an audit trail, and to assist in recovering from database weirdness e.t.c.

I'll flesh out more details here as I design it.

**Comment by tgreer** [comment]
I propose pushing the log via syslog to a syslog sever. Generally fairly reliable?

**Comment by mich181189** [comment]
> I propose pushing the log via syslog to a syslog sever. Generally fairly reliable?

yeah that's definitely a possibility. I was thinking a super simple text log, but actually that could be gained from syslog

**Comment by mich181189** [comment]
Closing because vending machine is very dead
