### ISSUE TITLE
existing maintainers should have maintainer like powers in the acserver

### ISSUE THREAD

**Issue by JasperWallace** [londonhackspace/acserver-django#7]
Needs to be integrated with django's permissions system.

u.permission_set.filter(permission=2).all() gives a list of tools that that user has maintainer on.

https://code.djangoproject.com/wiki/RowLevelPermissions
https://gist.github.com/tarkatronic/2030365
https://www.djangosnippets.org/snippets/1054/
http://www.csrdu.org/nauman/2012/12/16/row-level-permissions-in-django-admin/

https://github.com/dfunckt/django-rules

or maybe better:

https://github.com/django-guardian/django-guardian

**Comment by zymurgic** [comment]
Maintainers have been badgering for this.

**Comment by mich181189** [comment]
There's a bit more to come, but I've implemented the first part of this. I'll deploy once I've done the rest (allowing maintenance of permissions)

**Comment by mich181189** [comment]
ah what the hell, I'll deploy what I've got

**Comment by mich181189** [comment]
Ok, it requires a manual group (for now) but it should work I think

**Comment by mich181189** [comment]
I'll try out Django 2.2 on my test rig. Assuming it works, I'll be able to make use of some really useful new hooks to make this better and basically transparent to users
