### ISSUE TITLE
Logs Link

### ISSUE THREAD

**Issue by deanforbes** [londonhackspace/acserver-django#8]
The logs link is not active when I log in to the control panel @  /admin

![image](https://cloud.githubusercontent.com/assets/1895206/13056555/f6ab7aba-d40d-11e5-8cb0-6433d16059c0.png)

**Comment by JasperWallace** [comment]
Does it work now if you try again (might have to log in and out)?

**Comment by deanforbes** [comment]
Thanks sorted
